### ISSUE TITLE
Injecting references with declarative services

### ISSUE THREAD

**Issue by jhernandezgt** [hstaudacher/osgi-jax-rs-connector#103]
When trying to inject services into a Resource, the service always return null unless you defined the variable a static 
```
@Component
@Path("greeting")
public class GreetingResource {
    private  static Connector conn;
    @Reference()
    public void setConn(final Connector conn){
        this.conn = conn;
    }
```

but the question is if this in any way could generate a problem when the service is unbind ed??

**Comment by hstaudacher** [comment]
hi,
first how does this relate to the connector? I think this is a general problem you describe here. Maybe the mailing list of the OSGi implementation you use is the better place to ask this question.

As a side node. We are using the connector with Equinox and Equinox DS. All variables don't need to be static. So, this is not a connector problem.

**Comment by hstaudacher** [comment]
Please reopen if you think this is a connector problem.
