### ISSUE TITLE
Test 5.0 RC1

### ISSUE THREAD

**Issue by hstaudacher** [hstaudacher/osgi-jax-rs-connector#104]
The 5.0.0 RC1 is ready to be tested and includes the improvements for embedded devices (see #93).

Maven: https://oss.sonatype.org/content/repositories/snapshots/
ziped p2 repo: https://dl.dropboxusercontent.com/u/5808972/com.eclipsesource.jaxrs.repository-5.0.0RC1.zip

@kaikreuzer can you test it with openHAB?
@stefanseifert can you test the maven stuff? :)
@BryanHunt bnd repo also included in the zip archive ;)
@larsp can you test the new version with Swookie?

Will publish the release this friday if no-one vetoes or requests more time. Thanks guys!

**Comment by kaikreuzer** [comment]
Thanks @hstaudacher for putting this new RC together. I have tested it and it seems to work well - and it tremendously improves the startup time thanks to the work of @kolkoo! I am looking forward to the new release!

**Comment by hstaudacher** [comment]
Thanks @kaikreuzer ;)

**Comment by BryanHunt** [comment]
I did a basic test with https://github.com/BryanHunt/web-in-a-box and it is working.  Note that I had to clear the configuration area after upgrading.

**Comment by larsp** [comment]
@hstaudacher seems like the pom files are missing in the snapshot repo?

**Comment by hstaudacher** [comment]
Thanks guys for testing. No critical problems were reported, so I will try to release 5.0 this afternoon.

@larsp I don't get it. Are you talking about the snapshot p2 or maven repo?

**Comment by larsp** [comment]
It looks like as if the maven snapshot repo is missing poms and jars: https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/jaxrs/publisher/5.0-SNAPSHOT/

**Comment by hstaudacher** [comment]
oh I see. Regarding the feedback of the others I will continue with the release because with the central publishing everything works fine. Is this ok for you?

**Comment by larsp** [comment]
sure

**Comment by hstaudacher** [comment]
Release is done. Thank you all for participating in this small project ;)

5.0 p2 repo published and submitted to maven central! Here is the changelog: https://github.com/hstaudacher/osgi-jax-rs-connector/releases/tag/5.0.0

**Comment by kaikreuzer** [comment]
Just noticed that you might want to work on your versions within the p2 repo for the next release:
The jersey-feature has version 2.17, the bundle 2.18.
The jaxrs-connector is 5.0.0, the provider.gson 2.3.0 and the other providers 2.2.0. I would have expected them all to be 5.0.0?

(btw, what was the reason to jump from 2.3 to 5.0?)
