### ISSUE TITLE
Add support for Swagger

### ISSUE THREAD

**Issue by BryanHunt** [hstaudacher/osgi-jax-rs-connector#108]
I think [Swagger](http://swagger.io) would make a very nice addition to this framework.  I think the main challenge is in building a wrapper to expose the JAX-RS resources to the Swagger framework since it's based on annotations.

**Comment by thanhlq** [comment]
+1 

I have a small group in VN, when we have time we will try to study about this.

**Comment by hstaudacher** [comment]
every pull request is welcome ;). But please don't forget: No Tests -> No Merge ;)

**Comment by hstaudacher** [comment]
Will be tackled within the next 2 weeks

**Comment by BryanHunt** [comment]
Awesome.  I started looking at this a bit this morning.  If you want to collaborate, let me know.

**Comment by RadicalQuiver** [comment]
That's awesome ! It's been on my list of things to do for a while!

**Comment by thanhlq** [comment]
👍

**Comment by hstaudacher** [comment]
Managed to create an OSGi friendly integration. See
<img width="977" alt="screen shot 2015-11-08 at 12 05 47" src="https://cloud.githubusercontent.com/assets/289648/11019998/29344084-8611-11e5-9be6-73cee21c7c21.png">
Needs some more love. Will push it soon and create a snapshot for you guys to test it.

**Comment by hstaudacher** [comment]
Swagger support is implemented. I wrote a wiki page, see https://github.com/hstaudacher/osgi-jax-rs-connector/wiki/Swagger-Integration

The integration will be part of the upcoming 5.2 release.
