### ISSUE TITLE
Jackson MessageBodyWriters no longer available after upgrading from 4.2.1 to 5.1

### ISSUE THREAD

**Issue by RadicalQuiver** [hstaudacher/osgi-jax-rs-connector#116]
Previously we registered the Jackson ObjectMapper as follows

@Provider
@Component
public class JacksonObjectMapperProvider implements ContextResolver<ObjectMapper> {

	static ObjectMapper defaultMapper;
	static {
        defaultMapper = new ObjectMapper();
        defaultMapper.configure(SerializationFeature.INDENT_OUTPUT, true);
        defaultMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        defaultMapper.configure(SerializationFeature.WRITE_NULL_MAP_VALUES, true);        
	}
	
    @Override
    public ObjectMapper getContext(Class<?> type) {
        return defaultMapper;
    }
}

This no longer seems to work with 5.1.
(Using Jackson 2.5.3)
Suggestions ?

**Comment by hstaudacher** [comment]
uff, no idea. We didn't change anything except the Jersey version used. Maybe it's Jersey related?

**Comment by hstaudacher** [comment]
We use MessageBodyWriters for our gson provider too. So, I will close this because of no response. Please reopen if you feel this is a real issue of the connector.
