### ISSUE TITLE
Swagger throwing NoClassDefFoundError

### ISSUE THREAD

**Issue by BryanHunt** [hstaudacher/osgi-jax-rs-connector#123]
I'm trying to use Swagger in my environment and it's not working.  I tracked it down to io.swagger.jackson.ModelResolver line 212.  When it tries to load XmlRootElement, you get the NoClassDefFoundError.  I use XmlRootElement in another bundle and it seems to work just fine.  XmlRootElement for me is defined as part of the rt.jar in the JRE System Library.  Any ideas on what is going wrong?

**Comment by BryanHunt** [comment]
I think I figured out the problem.  The Swagger all bundle needs:

Import-Package: javax.xml.bind.annotation

**Comment by BryanHunt** [comment]
As an experiment, I hacked the swagger all bundle manifest and added javax.xml.bind.annotation to the Import-Package header and it's working now.

**Comment by hstaudacher** [comment]
ok, any version range we can specify?

**Comment by BryanHunt** [comment]
I have no idea on version range since it is part of the runtime.  I honestly don't fully understand why you even have to import it since it's part of the runtime.  Unless there's a definitive answer, I would leave the version range off.

**Comment by hstaudacher** [comment]
I observed such behaviour earlier. Form what I remember such thing shave always worked for me with equinox but for felix (karaf) I had to specify which runtime packages are available to bundles. Does this make sense? It happened a long time ago :)

**Comment by BryanHunt** [comment]
FYI, I'm using Felix and haven't tried with Equinox.
