### ISSUE TITLE
provider-swagger:jar:1.0 is not available in Maven Central.What should I do?

### ISSUE THREAD

**Issue by coverxiaoeye** [hstaudacher/osgi-jax-rs-connector#125]
provider-swagger:jar:1.0 is not available in Maven Central with the group id [com.eclipsesource.jaxrs](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.eclipsesource.jaxrs%22). What should I do? Thank you for any help!

**Comment by hstaudacher** [comment]
I must have forgotten it. Sorry about that. Will add it with the next release.

**Comment by coverxiaoeye** [comment]
Great！Looking forward to the next release.Thanks!

**Comment by hstaudacher** [comment]
Version 1.1 should be in central in a few hours.

**Comment by coverxiaoeye** [comment]
got it! I will write some practices recently. Thank you for your patience to answer!
