### ISSUE TITLE
Karaf feature should contain only jersey-min, not jersey-all

### ISSUE THREAD

**Issue by kaikreuzer** [hstaudacher/osgi-jax-rs-connector#126]
Is there a specific reason, why the Karaf feature uses jersey-all in https://github.com/hstaudacher/osgi-jax-rs-connector/blob/master/examples/karaf-integration/features/src/main/resources/features.xml#L5?

I would like to see a "light" version of this feature that only contains the jersey-min bundle. Not sure whether the current one could be changed or if we should define an additional feature for it.

**Comment by hstaudacher** [comment]
hmm, I'm wondering at all why we use our repackaged Jersey bundle here. I mean the only purpose for the -all and -min bundle for me was to make it easier to deal with it within Eclipse launch configurations, products and features.

For karaf you can actually use mvn dependencies from central. So, what do you think of refactoring the karaf feature to use the original Jersey artifacts?

As always, any pull request is welcome ;)

**Comment by kaikreuzer** [comment]
Thanks @hstaudacher!
