### ISSUE TITLE
Add support for Swagger annotations on interfaces

### ISSUE THREAD

**Issue by jkreutzfeld** [hstaudacher/osgi-jax-rs-connector#128]
The swagger provider works well when the Swagger annotations are on the implementation of the REST service. In our project, we use the annotations on the service interface though and this is where the DefaultJaxrsScanner fails because it only asks Jersey for the registered classes. Can you add support for this approach?

**Comment by hstaudacher** [comment]
Sure, good idea. Will add it to the planed features.
