### ISSUE TITLE
Invalid services defined in com.eclipsesource.jaxrs.jersey.min

### ISSUE THREAD

**Issue by dvanherbergen** [hstaudacher/osgi-jax-rs-connector#131]
The com.eclipsesource.jaxrs.jersey-min bundle contains service definitions in META-INF/services for service providers, which are not offered by the bundle.

When using this bundle with pax-web, pax-web scans the bundle for it services, finds the META-INF/services/javax.servlet.ServletContainerInitializer file that contains a reference to org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer. Next pax-web tries to load this class, but because it is not included in the bundle, it fails with a warning.

IMHO, the javax.servlet.ServletContainerInitializer file should be removed from the META-INF/services folder.

**Comment by dvanherbergen** [comment]
Sorry, I just rechecked and the class is indeed included in the jar, it appears there may be a problem with the class loading mechanism in pax-web.
So there is no problem with the build and this issue can be closed.

**Comment by hstaudacher** [comment]
ahh, if only any issue would solve itself :). Anyway thanks for reporting.
