### ISSUE TITLE
Customized SSLContext

### ISSUE THREAD

**Issue by diroza** [hstaudacher/osgi-jax-rs-connector#134]
Currently the jax-rs consumer comes with an implementation that trusts all certificates (see class `ClientHelper`). 
An enhancement would be the possibility to pass in a customized SSL context to have more control in trusting/accepting certificates. 
Maybe it would be even better to be able to pass in a complete `javax.ws.rs.client.Client` to get most flexibility.

**Comment by hstaudacher** [comment]
Thanks for the good idea
