### ISSUE TITLE
jax-rs-connector features referencing jax-rs-provider-swagger 1.0 instead of 1.1

### ISSUE THREAD

**Issue by jmacauley** [hstaudacher/osgi-jax-rs-connector#137]
I successfully installed the jax-es-connection feature within karaf:

    jax-rs-connector              | 5.3              | x         | osgi-jax-rs-connector    |                                                   
    jax-rs-provider-moxy          | 2.2              | x         | osgi-jax-rs-connector    |                                                   
    jax-rs-provider-gson          | 2.3              |           | osgi-jax-rs-connector    |                                                   
    jax-rs-provider-multipart     | 2.2              |           | osgi-jax-rs-connector    |                                                   
    jax-rs-provider-security      | 2.2              |           | osgi-jax-rs-connector    |                                                   
    jax-rs-provider-sse           | 2.2              |           | osgi-jax-rs-connector    |                                                   
    jax-rs-provider-swagger       | 1.0              |           | osgi-jax-rs-connector    |     

I have been trying to install the associated swagger feature, but 1.0 no longer exists in the repository. I checked features manifest and it still references swagger 1.0 instead of 1.1: 

    https://repo1.maven.org/maven2/com/eclipsesource/jaxrs/features/5.3/features-5.3-features.xml

    <feature name="jax-rs-provider-swagger" version="1.0">
        <bundle dependency="true">mvn:com.eclipsesource.jaxrs/swagger-all/1.5.5</bundle>
        <bundle>mvn:com.eclipsesource.jaxrs/provider-swagger/1.0</bundle>        
    </feature>

Am I doing something wrong or is this in fact an oversight?

**Comment by hstaudacher** [comment]
I think it's an oversight. Will be fixed in the next version

**Comment by hstaudacher** [comment]
Should be fixed in maven central within the next hour
