### ISSUE TITLE
Consumer calls slow

### ISSUE THREAD

**Issue by miguelalvarado** [hstaudacher/osgi-jax-rs-connector#140]
Hi,
I am using the ConsumerPublisher on Apache Felix. When I execute a call of the Resource I have published it takes 5.7 seconds, when I execute the same call using a regular HTTP Client, it takes only 0.6 seconds.
Is this a known performance issue? Or are there any parameters that I should configure to optimize the performance of the Consumers? Please let me know if adding the code will help to clarify.

Regards, Miguel

**Comment by hstaudacher** [comment]
Adding some example will help. It would be awesome to see 2 unit tests that do the same, one for the consumer, one for a regular client.

**Comment by miguelalvarado** [comment]
Closing this, the latency on the response was due to my local Vagrant.
