### ISSUE TITLE
Errors in package versioning

### ISSUE THREAD

**Issue by doggy-dev** [hstaudacher/osgi-jax-rs-connector#145]
Hello,

I'm using the jax-rs-connector and today I updated my dependency to 5.3.1. Now I see that some major versions have been incremented from 4 to 5: 
Export-Package: com.eclipsesource.jaxrs.publisher;version="5.3.1" earlier "4.x.x". Now my dependency Import-Package: com.eclipsesource.jaxrs.publisher;version="[4.3.0,5.0.0)" doesn't work anymore. There are no changes in the package so I see no need to increment the major version. Was there a particular reason for the version change?

**Comment by hstaudacher** [comment]
We keep the package versions in sync with the bundle versions. It's just how it was done from the very beginning. I know in your situation this sucks but I think introducing a different policy now is bad as well. Sorry about that.
