### ISSUE TITLE
Custom default path for services

### ISSUE THREAD

**Issue by madhugarimilla** [hstaudacher/osgi-jax-rs-connector#151]
I see the current default path for all services is '/services'. Can we set this to something of our choice?

**Comment by hstaudacher** [comment]
Check the faq https://github.com/hstaudacher/osgi-jax-rs-connector/wiki/FAQ

**Comment by madhugarimilla** [comment]
Hi,

I was trying to provide the root like this inside start method of Activator class. Did i miss something? my services are still available under /services.

`ServiceReference<?> reference = context.getServiceReference( ConfigurationAdmin.class.getName() );
ConfigurationAdmin configAdmin = ( ConfigurationAdmin )context.getService( reference );
Configuration configuration = configAdmin.getConfiguration( "com.eclipsesource.jaxrs.connector", null );
Dictionary<String, Object> properties = configuration.getProperties();
properties.put( "root", "/rest/v1" ); 
configuration.update();
context.ungetService( reference );`
