### ISSUE TITLE
Support for swagger ui with osgi-jax-rs-connector

### ISSUE THREAD

**Issue by madhugarimilla** [hstaudacher/osgi-jax-rs-connector#152]
Hi, Do we have support for swagger to the services exposed using osgi-jax-rs-connector? Could you please point me to an example. Can we use the swagger ui inside eclipse rap?

**Comment by hstaudacher** [comment]
Yes, you have swagger support. Just start the swagger.provider bundle and go to /services/swagger.json (or another root path). I have no idea how rap is related to the swagger ui. Maybe you can use it in a browser widget.
