### ISSUE TITLE
Missing Import-Package org.eclipse.persistence.internal.jaxb.many in jersey-all/jersey-min

### ISSUE THREAD

**Issue by cyrilballagny** [hstaudacher/osgi-jax-rs-connector#174]
Hi,
I am building some REST services with JSON serialization/deserialization relying on MOXy.
An exception  NoClassDefFoundError is thrown related to org.eclipse.persistence.internal.jaxb.many.CollectionValue when JAXB marshaller is created.
Adding org.eclipse.persistence.internal.jaxb.many to list of Import-Packages in jersey-min and jersey-min fixes this issue.
Could you add this import package statement when building Jersey-All and Jersey-Min
(Maybe some other packages related to jaxb are missing but not used in my case)
In any case, Thank you very much for your effort!

**Comment by BryanHunt** [comment]
Adding an import to jersey would couple it to MOXy and that is the wrong way to go.  I would bring this issue up with the MOXy developers.

**Comment by cyrilballagny** [comment]
Indeed, I understand your point.
Thank you for this quick answer.
