### ISSUE TITLE
Forking this project

### ISSUE THREAD

**Issue by BryanHunt** [hstaudacher/osgi-jax-rs-connector#178]
I'm considering the possibility of forking this project.  @hstaudacher has done a great job on this code, but I suspect his new job does not afford him the time to continue to maintain this code.  I use this code for production applications at work and I would like to ensure the project remains supported.  Please comment here with your feedback good or bad.  Also, if this project were to be forked, would anyone want to sign up as a co-contributor?

**Comment by hstaudacher** [comment]
@BryanHunt you are right, I have not much time left. I think forking is not that good. What about contributor permission for you on this project?

**Comment by BryanHunt** [comment]
@hstaudacher I'd be ok with contributor permission if you are ok with me converting the project to Bndtools + gradle (I can't stand Maven).

**Comment by hstaudacher** [comment]
sounds good to me. Do you think it's possible to also provide a p2 repo when doing a release? I think we have a lot of users using p2 as well.

**Comment by BryanHunt** [comment]
Yes, we can still provide a p2 repo.
