### ISSUE TITLE
Different provider import definitions for 'org.osgi.framework'

### ISSUE THREAD

**Issue by dfelski** [hstaudacher/osgi-jax-rs-connector#184]
Currently you can find the following import package definitions for the available JAX-RS provider features:

com.eclipsesource.jaxrs.provider.moxy
com.eclipsesource.jaxrs.provider.gson
com.eclipsesource.jaxrs.provider.security
`Import-Package: ... , org.osgi.framework;version="[1.3.0,2.0.0)"`

com.eclipsesource.jaxrs.provider.sse
com.eclipsesource.jaxrs.provider.swagger
`Import-Package: ... , org.osgi.framework;version="[1.2.0,2.0.0)"`

com.eclipsesource.jaxrs.provider.multipart
`Import-Package: ... , org.osgi.framework;version="1.3.0"`

Especially the last one is not usable e.g in current version of Apache Felix, which exports that package in version 1.8. Is there a reason for that definition? Changing it to `org.osgi.framework;version="[1.3.0,2.0.0)"` seems to fix that issue.

**Comment by doggy-dev** [comment]
If I recall correctly version="1.3.0" means every version from 1.3.0 on... this is not a restricttion to 1.3.0 only. But this may be an Equinox interpretation of the version, I don't know how Felix behaves.

**Comment by dfelski** [comment]
You're absolutely right, I missed that detail. But what could be the reason for that behavior then? I don't think Felix deals with that completely different.

**Comment by doggy-dev** [comment]
Unfortunately I didn't quite understand what is your issue other than continuity in the package import versioning.
Check if you have more than one bundle providing the package _org.osgi.framework_ installed and resolved in your osgi container.

**Comment by dfelski** [comment]
I would say, just ignore it for now, I have to recheck my configuration and collect more information to understand my issue. Thank you for your help.
