### ISSUE TITLE
connector does not work when bundle uses Blueprint

### ISSUE THREAD

**Issue by bbarin** [hstaudacher/osgi-jax-rs-connector#64]
If a bundle register a JAX-RS resource as a service using Blueprint the connector is unable to track and publish the resource.

**Comment by mhshams** [comment]
I'm experiencing the same issue. apparently blueprint proxies are not detected by connector.
```
WARNING: The (sub)resource method foo in Proxy3af1b149_8c2f_488c_82c3_6357ee4a3aff contains empty path annotation.
```

**Comment by kdoteu** [comment]
Blueprint (Gemini.Blueprint) in combination with the connector is working for me.
With this snipped 
	<bean class="xxx.api.notification.SingleNotificationApi"
		id="singleNotificationApi">
		<property name="notificationManager" ref="notificationsManager" />
	</bean>

	<service id="serviceSingleNotification"
		interface="xxx.api.notification.ISingleNotificationApi"
		ref="singleNotificationApi">
	</service>
I register the service.
Don't know if this helps you.

**Comment by hstaudacher** [comment]
hmm, working or not working, that;s the question :)

I will close the issue now because of @kdoteu comment. Please reopen if this is still a problem.
