### ISSUE TITLE
MessageBodyWriter not found on Raspberry Pi

### ISSUE THREAD

**Issue by hstaudacher** [hstaudacher/osgi-jax-rs-connector#72]
It seems that the Gson Provider can't be registered on a Raspberry Pi. It results in `MessageBodyWriter not found` when accessing a resource that produces json. 

This was discussed in #67 and #68

**Comment by kaikreuzer** [comment]
This issue is becoming more urgent to me by now. Do you have any idea, when you might find the time or how I could help? Sorry for pushing ;-)

**Comment by hstaudacher** [comment]
No problem. My new pi arrived on wednesday. I hope I can work on it next monday

**Comment by hstaudacher** [comment]
Sorry once more for the delay. We are in a hot phase for the release of tabrisjs.com and it's hard to find time to work on this project right now. I hope I can make it this week.

**Comment by kaikreuzer** [comment]
No worries - we think we have solved it and will create a PR for it this morning. All we would like you to do is to review it briefly and eventually create the 4.2 release then :-)

**Comment by hstaudacher** [comment]
Oh nice to hear ;)

**Comment by kaikreuzer** [comment]
I have successfully tested the startup on both Raspberry Pi 1 and Raspberry Pi 2 with the fix provided by https://github.com/hstaudacher/osgi-jax-rs-connector/pull/80 and can confirm that the problem is solved by it.

**Comment by hstaudacher** [comment]
Fixed with the merge of pull request #80
