### ISSUE TITLE
P2 site not found

### ISSUE THREAD

**Issue by jmarreroc** [hstaudacher/osgi-jax-rs-connector#74]
Hi Holger!

I'm having problems when i include the p2 site (http://hstaudacher.github.io/osgi-jax-rs-connector) in my targetplatform. Do I need to consider something new to make it work? I have the problem in Eclipse Kepler and Juno, and both inside or outside my organization domain.

Thank you very much for your time your great work!

**Comment by hstaudacher** [comment]
Fixed -> Closing.
