### ISSUE TITLE
Repo index needs to be updated

### ISSUE THREAD

**Issue by BryanHunt** [hstaudacher/osgi-jax-rs-connector#78]
The repo index needs to be updated with the latest version to support Bndtools

**Comment by hstaudacher** [comment]
Will be done with the 4.2.0 release. Probably today

**Comment by hstaudacher** [comment]
Hey Bryan, I think we can use this issue to discuss the problem. I used this command to generate the file:

`java -jar org.osgi.impl.bundle.repoindex.cli-0.0.4.jar -n osgi-jax-rs 4.2.0/plugins/*`

Any idea what is wrong?

**Comment by BryanHunt** [comment]
My bad, I didn't add the repo to bndtools correctly and assumed the empty index.xml was the problem.  The .gz is fine.

**Comment by hstaudacher** [comment]
phew. Ok good to hear. So I will close this issue as well. Thanks for testing
