### ISSUE TITLE
jax-rs api not working with bndtools

### ISSUE THREAD

**Issue by BryanHunt** [hstaudacher/osgi-jax-rs-connector#82]
When I add the jersey all bundle to my build path, bndtools can't resolve the jax-rs apis.

**Comment by BryanHunt** [comment]
I verified that using jersey all 2.10.1.SR1 works and 2.16.0 does not work.

**Comment by hstaudacher** [comment]
Do you have any idea why? Not much has changed in the jersey-all build

**Comment by hstaudacher** [comment]
Btw. I tried it using p2 and equinox and everything works.

**Comment by hstaudacher** [comment]
I would say we release 4.2 and publish a service release as soon as we know what is wrong.

**Comment by BryanHunt** [comment]
One immediate difference I see is that the 2.10 version has javax at the root of the jar in addition to being embedded as a jar in target/dependency

**Comment by hstaudacher** [comment]
Hey @BryanHunt,
can you test the latest version? I changed the all bundle to not use the embed stuff anymore.

**Comment by BryanHunt** [comment]
It works.  Thanks.

**Comment by hstaudacher** [comment]
Alright :). Good to hear. Will close the issue.
