### ISSUE TITLE
Provide test-bundle

### ISSUE THREAD

**Issue by kdoteu** [hstaudacher/osgi-jax-rs-connector#87]
I want to do some tests like explained in https://jersey.java.net/documentation/latest/test-framework.html#d0e16861.
But there is no bundle which provide "JerseyTest" or the package "org.glassfish.jersey.test" as far I can see.

So please provide the package "org.glassfish.jersey.test" in the jersey-all bundle

Or is there an other way to test a jersey-service?

**Comment by hstaudacher** [comment]
I think it's not a good idea to include the test bundle in Jersey all. This means we mix the runtime lib with test libs which is not good practice.

You have two options:

1) Just add the bundle yourself. Jersey ships as OSGi bundles. The jersey-all bundle is just a helper to not have 20 bundles or so. But you can also use the original Jersey bundles and therefore also the test bundle.
2) Use another library to test your services e.g. [restfuse](http://developer.eclipsesource.com/restfuse/) (not maintend anymore) or [rest-assured](https://github.com/jayway/rest-assured) or [rest-driver](https://github.com/rest-driver/rest-driver)

**Comment by hstaudacher** [comment]
Will close this issue because I think it's out of discussion to include the test bundle in our target. Please reopen if you disagree ;)
